Intro:

Diagrams: https://yuml.me/diagram/scruffy/class/draw

Who am I, what have I done.
Twitter best place to contact, or mail ian.miell@gmail.com / meirionconsulting?
No-one ever taught me bash.

Boundaries - introduction, so advanced questions won't be answered.
However, even experienced users can get something out of it

Target audiences and what you'll get out of it:

- hardly used bash    => will get a coverage of main areas of bash interest
- used bash somewhat  => refresher, and explain a few things seen before
- used bash for years => 'aha moments' - I'd always wondered about that!

Poll: experience level

- never used bash
- used bash for < 2 years
- used bash for < 5 years
- used bash for < 10 years
- used bash for > 10 years

Use group chat with a +- to indicate yes/no. Practice this?

72 slides

Map of the course, refer back to it as we go through.

Lots of screensharing.

Prereqs/software required:

 bash version 4+
 grep
 an editor (i prefer vim)
 rename

Where to get these?


==============

Structure of the course.


Part I - Fundamentals
DISCUSSION - what to do with bash?
1.intro.md
1.1.bash_core.md
1.3.variables.md
1.2.globbing.md
EXERCISE 1
1.5.pipes_redirects.md
EXERCISE 2
DISCUSSION - recap
BREAK

Part II - Fundamentals II
DISCUSSION - what is a programming language? is bash a programming language?
2.4.exit_codes.md
2.2.tests.md
2.3.loops.md
1.4.functions.md
EXERCISES 3
2.1.command_substitution.md
2.6.file_substitution.md
DISCUSSION - recap
BREAK

Part III - Scripting
1.6.scripts_and_startup.md
2.5.set.md
4.2.debugging.md
EXERCISE 4 - examine own startup
2.7.subshells.md
2.8.ifs.md
EXERCISE 5 - write a script
DISCUSSION - recap
BREAK

Part IV - Advanced
4.1.traps.md
EXERCISE 6 - script you can't escape
4.3.string_manipulation.md
4.4.autocomplete.md
DISCUSSION - walthrough ci script
4.5.cheapci.md


Bash Basics I (50-55 minutes)

Discussion: 5 minutes
What do you want to do with bash (see recommended preparation above)?
Presentation: What is bash, basics part I (globbing, variables) - 15 minutes
Exercise: 10 minutes
Globbing challenge
Shell variable research
Presentation: Basics, part II (pipes and redirects) - 10 minutes
Exercise: 10 minutes
Pipes and redirect challenges
Discussion: 5 minutes
Recap material

Break (5 minutes)

Bash Basics II (50-55 minutes)
Discussion: 5 minutes
What is a programming language? Is bash a programming language?
Presentation: Exit codes, tests, loops, functions - 25 minutes
Exercise: 10 minutes
Write function that works over files in a folder
Presentation: Command and file substitution - 15 minutes
Discussion: 5 minutes
Recap material

Break (5 minutes)

Scripting Bash (50-55 minutes)
Presentation: Scripts and Startup, Shell Options, Debugging - 20 minutes
Exercise: 10 minutes
Examine your own startup
Change startup to add options, see what happens
Presentation: Subshells, IFS - 10 minutes
Exercise: 10 minutes
Write script to deal with sets of folders with spaces in filenames
Discussion: 5 minutes
Recap material

Break (5 minutes)

Advanced Bash (50-55 minutes)
Presentation: Trapping and signals - 15 minutes
Exercise: 10 minutes
Script you can’t escape?
Presentation: String manipulation, autocomplete - 15 minutes
Discussion: 10 minutes
Walk-through of ‘cheapci’ script

